package com.fenji.scoretrace.ui.theme

import androidx.compose.ui.graphics.Color

// 浅色（设计稿 v1：浅灰蓝页底 + 纯白卡片 + 青蓝品牌色）
val PrimaryLight = Color(0xFF3B82F6)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFDBEAFE)
val OnPrimaryContainerLight = Color(0xFF1E40AF)
val SecondaryLight = Color(0xFF64748B)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE2E8F0)
val OnSecondaryContainerLight = Color(0xFF334155)
val TertiaryLight = Color(0xFF7C5CFC)
val OnTertiaryLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFEEF1F8)
val OnBackgroundLight = Color(0xFF1A1A2E)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF1A1A2E)
val SurfaceVariantLight = Color(0xFFF1F5F9)
val OnSurfaceVariantLight = Color(0xFF64748B)
val OutlineLight = Color(0xFFE2E8F0)
val OutlineVariantLight = Color(0xFFF1F5F9)
val ErrorLight = Color(0xFFEF4444)
val OnErrorLight = Color(0xFFFFFFFF)

// 浅色下的分层表面（卡片之外仍有层级）
val SurfaceContainerLight = Color(0xFFFFFFFF)
val SurfaceContainerHighLight = Color(0xFFF8FAFC)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF8FAFC)
val SurfaceContainerHighestLight = Color(0xFFF1F5F9)
val SurfaceDimLight = Color(0xFFE2E8F0)
val SurfaceBrightLight = Color(0xFFFFFFFF)

// 深色（slate 蓝黑体系：层次更清晰、深色下更精致）
val PrimaryDark = Color(0xFFA9C7FF)
val OnPrimaryDark = Color(0xFF003062)
val PrimaryContainerDark = Color(0xFF00458A)
val OnPrimaryContainerDark = Color(0xFFD6E3FF)
val SecondaryDark = Color(0xFFBEC6DC)
val OnSecondaryDark = Color(0xFF283041)
val SecondaryContainerDark = Color(0xFF334155)
val OnSecondaryContainerDark = Color(0xFFDAE2F9)
val TertiaryDark = Color(0xFFDCBCE0)
val OnTertiaryDark = Color(0xFF3F2844)
// 深色下页面与卡片拉开层次：页底 #0F172A、卡片 #1E293B、描边 #334155
val BackgroundDark = Color(0xFF0F172A)
val OnBackgroundDark = Color(0xFFF1F5F9)
val SurfaceDark = Color(0xFF1E293B)
val OnSurfaceDark = Color(0xFFF1F5F9)
val SurfaceVariantDark = Color(0xFF334155)
val OnSurfaceVariantDark = Color(0xFF94A3B8)
val OutlineDark = Color(0xFF64748B)
val OutlineVariantDark = Color(0xFF334155)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)

// 深色下的分层表面
val SurfaceContainerDark = Color(0xFF1E293B)
val SurfaceContainerHighDark = Color(0xFF293548)
val SurfaceContainerLowestDark = Color(0xFF0B1220)
val SurfaceContainerLowDark = Color(0xFF172033)
val SurfaceContainerHighestDark = Color(0xFF334155)
val SurfaceDimDark = Color(0xFF0B1220)
val SurfaceBrightDark = Color(0xFF334155)
